config/routes.rb
RegisterProductManufacturer::Application.routes.draw do

  resources :products
  resources :manufacturers
  resources :users
  resources :session, :only => [:new, :create, :destroy]
  resources :offers, :only => [:index, :show]
  resources :orders
  resources :items

  post 'cart/items/:id' => 'cart#add_product'
  delete 'cart/items/:id' => 'cart#destroy'
  get 'cart' => 'cart#show'
  post 'checkout' => 'cart#checkout'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  # has_many :items
  # attr_reader :items

  # def initialize
  #   @items = []
  # end

  # def add_product(product)
  #   @items << product
  # end

end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_accessible :quantity, :product_id, :order_id

  belongs_to :order

  belongs_to :product

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :products
  attr_accessible :name
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user_id
  belongs_to :user
  has_many :items
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :manufacturer
  has_many :items

  attr_accessible :description, :name, :photo, :manufacturer_id

  mount_uploader :photo, ImageUploader

  paginates_per 10

  # validates_presence_of :manufacturer_id

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def map_items_cart #devera retornar uma instancia do array de cart
    Product.order(:name).find( session[:cart] )#buscara no banco somente os produtos que estiverem no array pelo id de cada
    # produto e o retorno sera uma instancia com todos os elementos deste array onde sera possivel acessar os atributos destes
    # objetos tanto pelo id quanto pelo nome na pagina de index onde o metodo e chamado.
  end

  def current_user
    User.find(session[:email_id]) if session[:email_id]
  end

  helper_method :map_items_cart, :current_user

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  respond_to :html, :json, :pdf

  def add_product #metodo para adicionar produto no carrinho

    (session[:cart] ||= []) << params[:id] #se variavel session[:cart] estiver vazia recebera array vazio
    p "cart items: #{session[:cart]}"   # imprime a secao
    render :nothing => true  #necessita renderizar algo na tela senao da erro

  end

  def destroy

    session[:cart].delete(params[:id])  # na secao do cart chama o metodo delete passando o id
    p "cart items: #{session[:cart]}" # imprime na tela a secao
    render :nothing => true #necessita renderizar algo na tela senao da erro

  end

  def checkout
    if session[:email_id]
      @order = Order.create user_id: session[:email_id]

      session[:cart].map do |i|
        Item.create order_id: @order.id, product_id: i, quantity: params["#{:product}_#{i}"][:quantity]
      end
      Notifier.send_order(@order).deliver
      respond_with @order
    else
      redirect_to new_session_path
    end
  end

  def show
    @order = Order.new
    session[:cart].map do |i|
      @order.items.build product_id: i
    end
    render 'show'
  end

end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  respond_to :html

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    respond_with @manufacturer = Manufacturer.create(params[:manufacturer])
  end

  def show
    respond_with @manufacturer = Manufacturer.find(params[:id])
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def update
    respond_with @manufacturer = Manufacturer.update(params[:id], params[:manufacturer])
  end

  def index
    respond_with @manufacturers = Manufacturer.all
  end

  def destroy
    respond_with @manufacturer = Manufacturer.destroy(params[:id])
  end

  def map_manufacturers
    Manufacturer.all
  end
  helper_method :map_manufacturers

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  respond_to :html, :json

  def index
    respond_with @products = Product.order('name').page(params[:page])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  respond_to :html

  def show
    respond_with @order = Order.find(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  respond_to :html

  def new
    respond_with @product = Product.new
  end

  def create
    respond_with @product = Product.create(params[:product])
  end

  def show
    respond_with @product = Product.find(params[:id])
  end

  def index
    respond_with @products = Product.order('name').page(params[:page])
  end

  def destroy
    respond_with @product = Product.destroy(params[:id])
  end

  def edit
    respond_with @product = Product.find(params[:id])
  end

  def update
    respond_with @product = Product.update(params[:id], params[:product])
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  respond_to :html, :json

  def new
    @session = User.new
  end

  def create

    @session = User.find_by_email(params[:user][:email])

    if @session && User.authenticate(@session.email, params[:user][:password])
      session[:email_id] = @session.id
      redirect_to users_path
    else
      respond_with @session, location: new_session_path
    end
  end

  def destroy
    session[:email_id] = nil
    redirect_to new_session_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  respond_to :html, :json

  def new
    respond_with @session = User.new
  end

  def create

    @session = User.find_by_email(params[:user][:email])

    if @session && User.authenticate(@session.email, params[:user][:password])
      session[:email_id] = @session.id
      redirect_to users_path, {:notice => "#{@session.email} was logged with success!"}

    else
      redirect_to new_session_path, {:notice => "Invalid user or password!"}
    end

  end

  def destroy
    session[:email_id] = nil
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :json

  def new
    respond_with @user = User.new
  end

  def show
    respond_with @user = User.find(params[:id])
  end

  def create
    respond_with @user = User.create(params[:user])
  end

  def index
    respond_with @users = User.all
  end

  def destroy
    respond_with @user = User.destroy(params[:id])
  end

  def edit
    respond_with @user = User.find(params[:id])
  end

  def update
    respond_with @user = User.update(params[:id], params[:user])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/i18n_helper.rb
module I18nHelper

  def t_model model
    model.to_s.camelize.constantize.model_name.human
  end

  def t_model_plural model
    model.to_s.camelize.constantize.model_name.human(count: 2)
  end

  def t_model_attribute model, attribute
    model.to_s.camelize.constantize.human_attribute_name attribute
  end

end

app/views/cart/show.html.haml
%table
  %thead
    %tr
      %th= t_model_attribute :item, :name
      %th= t_model_attribute :item, :quantity

  %tbody
    = form_tag "/checkout", method: 'post' do
      - @order.items.each do |i|
        %tr
          %td= i.product.name
          %td= text_field "product_#{i.product.id}", :quantity
        %tr
          %td= submit_tag 'Finish purchase'

app/views/checkout/show.html.haml
= link_to 'email a friend', '#', onclick => "$('#{finish_purchase_form}').slideDown()"
= render 'finish_purchase'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>RegisterProductManufacturer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <!-- posteriormente criada -->
    <%= notice %>

    <!-- div para exibir na pagina o current_user, que servira para autenticar o login na sessao -->
    <div id="session_id">
      <%= current_user.email if current_user %>
    </div>

  </body>

</html>

app/views/layouts/application.html.haml
%head{lang: 'pt-BR'}
  %title
    Sample Cart

  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

= yield

#session
  - if current_user
    User session:
    = current_user.email
    = link_to I18n.t('helpers.link.sign_out'), new_session_path, :method => :delete

app/views/manufacturers/_form.html.haml
=simple_form_for @manufacturer do |f|
  =f.input :name
  =f.submit

app/views/manufacturers/edit.html.haml
%h1=t('title.edit.manufacturer')

=render 'form'

=link_to t('action.list'), manufacturers_path

app/views/manufacturers/index.html.haml
%h1=t('title.index.manufacturer')
%table
  %tr
    %th=t('activerecord.attributes.manufacturer.name')
  - map_manufacturers.each do |manufacturers|
    %tr
    %td= manufacturers.name
    %td= link_to t('action.show'), manufacturer_path(manufacturers)
    %td= link_to t('action.edit'), edit_manufacturer_path(manufacturers)
    %td= link_to t('action.destroy'), manufacturers, method: :delete, data:{confirm: t('general.are_you_sure')}
%br
= link_to t('action.new'), new_manufacturer_path

app/views/manufacturers/new.html.haml
%h1=t('title.new.manufacturer')

=render 'form'

=link_to t('action.list'), manufacturers_path

app/views/manufacturers/show.html.haml
%h1=t('title.show.manufacturer')

= "#{t_model_attribute :manufacturer, :name}:"

= @manufacturer.name

%br

= link_to t('action.edit'), edit_manufacturer_path(@manufacturer)

= link_to t('action.list'), manufacturers_path

app/views/notifier/email_friend.html.erb
Notifier#email_friend

<%= @greeting %>, find me in app/views/app/views/notifier/email_friend.text.erb

app/views/notifier/send_order.html.haml
%head
  %title
    Sample Cart

  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  / = csrf_meta_tags

= yield

= render 'shared/order', layout: false, order: @order

app/views/offers/index.html.haml
%h1=t('title.index.product').capitalize

#cart
  Cart
  %ol
    - if session[:cart]
      - map_items_cart.each do |p|

        %li{ id: "product_#{p.id}" }
          = p.name
          %a{ href: '#' } x

= paginate @products

%ul
  - @products.each do |p|

    %li.draggable{id: "product_#{p.id}"}
      = link_to p.name, p

app/views/products/_form.html.haml
=simple_form_for @product do |f|
  =f.association :manufacturer
  =f.input :name
  =f.input :description
  =f.input :photo, :label => "photo", :as => :file
  =f.button :submit

app/views/products/edit.html.haml
%h1=t('title.edit.product')

= render 'form'

app/views/products/index.html.haml
%h1=t('title.index.product')

= paginate @products

%table
  %thead
    %tr
      %th=t('activerecord.attributes.product.manufacturer')
      %th=t('activerecord.attributes.product.name')
      %th=t('activerecord.attributes.product.description')
  %tbody
    - @products.each do |product|
      %tr{id: "product_#{product.id}"}
      %td= product.manufacturer.name
      %td= product.name
      %td= product.description
      %td= link_to t('action.show'), product_path(product)
      %td= link_to t('action.edit'), edit_product_path(product)
      %td= link_to t('action.destroy'), product, method: :delete, data:{confirm: t('general.are_you_sure')}
%br
= link_to t('action.new'), new_product_path

app/views/products/new.html.haml
%h1=t('title.new.product')

= render 'form'

app/views/products/show.html.haml
%h1=t('title.show.product')
%br

= "#{t_model_attribute :product, :name}:"
= @product.name

%br
= image_tag @product.photo
%br

= "#{t_model_attribute :manufacturer, :description}:"
= @product.description

%br
%br
= link_to t('action.edit'), edit_product_path(@product)
= link_to t('action.list'), products_path

app/views/session/_form.html.haml
= simple_form_for @session, html: {id: 'form'}, url: session_index_path do |f|
  = f.input :email
  = f.input :password
  = f.submit "Sign In"

app/views/session/new.html.haml
%h1 Sign in

= render 'form'

= link_to 'New User', new_user_path

app/views/shared/_order.html.haml
%h1 Order

Email:
= order.user.email

-if order.items.any?
  %h1 Items

  %table
    %thead
      %tr
        %th Name
        %th Quantity

    %tbody
      - order.items.each do |i|
        %tr{id: "item_#{i.id}"}
          %td= i.product.name
          %td= i.quantity

app/views/users/_form.html.haml
=simple_form_for @user do |f|
  =f.input :email
  =f.input :password
  =f.input :password_confirmation
  =f.button :submit

app/views/users/edit.html.haml
%h1= t('title.edit.user')

=render 'form'

=link_to t('action.list'), users_path

app/views/users/index.html.haml
%h1= t('title.index.user')
%table
  %tr
    %th= t('header.index.user')
  - @users.each do |user|
    %tr
      %td= user.email
      %td= link_to t('action.show'), user_path(user)
      %td= link_to t('action.edit'), edit_user_path(user)
      %td= link_to t('action.destroy'), user, method: :delete, :data => {confirm: t('general.are_you_sure')}

%br

=link_to t('action.new'), new_user_path

app/views/users/new.html.haml
%h1=t('title.new.user')

= render 'form'

app/views/users/show.html.haml
=t('header.show.user')
= @user.email
%br

 = link_to t('action.edit'), edit_user_path(@user)
 = link_to t('action.list'), users_path